In [2]:
import numpy as np
arr=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
print(arr)
arr[0,3:5]

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


array([3, 4])

In [3]:
arr=np.array(([0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]))
#print(arr)
#arr[:,2]
arr.ndim

2

In [2]:
arr=np.array(([0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]))
print(arr)
arr[-4:,-4:]

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


array([[22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45],
       [52, 53, 54, 55]])

In [24]:
arr=np.array(([0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]))
print(arr)
arr[2::2,::2]

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


array([[20, 22, 24],
       [40, 42, 44]])

# ARRAY FUNCTIONS

In [5]:
b=np.arange(1,11)
print(b)

b>4 #it checks the values in the array b and returns true >4 and false <4

[ 1  2  3  4  5  6  7  8  9 10]


array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [29]:
bool_arr=b>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [30]:
b[bool_arr] #calling the bool_var and here it returns the true values

array([ 5,  6,  7,  8,  9, 10])

In [6]:
c=4
b[b>4]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
b+b#it adds both the array values


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [34]:
b1=b
1/b1

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [35]:
b1**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
2**3

8

In [36]:
np.sqrt(b1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [37]:
np.exp(b1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [38]:
np.sin(b1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [39]:
np.log(b1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [40]:
b1.sum()

55

In [41]:
b1.mean()

5.5

In [42]:
b1.max()

10

In [10]:
arr.min()

array([0, 1, 2, 3, 4, 5])

In [46]:
b1.var()

8.25

In [45]:
b1.std()

2.8722813232690143

In [50]:
arr
arr.sum(axis=0)#it prints the column wise sum values

array([150, 156, 162, 168, 174, 180])

In [62]:
arr
arr.sum(axis=1)#it prints the row wise sum values

array([ 15,  75, 135, 195, 255, 315])

# pandas

In [2]:
import numpy as np
import pandas as pd

In [65]:
myindex=["E5221005","E5221034","E5221037"]
mydata=['jaisurya','venkat','gulshan']
#                   data           labeled index
namelist=pd.Series(data=mydata,index=myindex)#series coverts the data into "tabular format"
namelist


E5221005    jaisurya
E5221034      venkat
E5221037     gulshan
dtype: object

In [66]:
pd.Series(data=mydata)#it automatically generates the "numeric label" when labelled index not given
#numeric 
#index

0    jaisurya
1      venkat
2     gulshan
dtype: object

In [13]:
#                      start end values
ran_data=np.random.randint(0,100,4)
ran_data

array([74, 73, 63, 50])

In [14]:
names=['sam','ram','black','jin']
ages=pd.Series(ran_data,names)
ages

sam      74
ram      73
black    63
jin      50
dtype: int32

In [71]:
#    data:labelled index
age={"sam":10,"ram":20,"tom":40}
pd.Series(age)

sam    10
ram    20
tom    40
dtype: int64

In [1]:
a={'DA':15,'AIDA':15,'AS':15,'DM':14}#dictionaries
b={'DA':15,'AIDA':15,'AS':15,'dm':14}#dictionaries
CA1=pd.Series(a)
CA1

NameError: name 'pd' is not defined

In [109]:
CA2=pd.Series(b)
CA2

DA      15
AIDA    15
AS      15
dm      14
dtype: int64

In [110]:
a['DA']#accesig using key

15

In [111]:
CA1[2]#accesing using index after assigning it a new var"CA1"

15

In [24]:
CA1.keys()

Index(['DA', 'AIDA', 'AS', 'DM'], dtype='object')

In [113]:
CA1*2

DA      30
AIDA    30
AS      30
DM      28
dtype: int64

In [114]:
CA1+CA2

AIDA    30.0
AS      30.0
DA      30.0
DM       NaN
dm       NaN
dtype: float64

In [115]:
CA1.add(CA2,fill_value=0) #it prints their values instead of 'nan'

AIDA    30.0
AS      30.0
DA      30.0
DM      14.0
dm      14.0
dtype: float64

In [138]:
np.random.seed(190)#it stores this random matrix into seed 190
#                          it creates matrix 
mydata = np.random.randint(0,101,(4,3))
mydata

array([[ 78,  12,  43],
       [ 37,  88,   3],
       [ 87,  20,  71],
       [  6, 100,  93]])

In [139]:
mysub=['DA','AI','AS','DIA']
mycol=['CA1','CA2','CA3']


In [142]:
df=pd.DataFrame(data=mydata,index=mysub,columns=mycol)
df

CA1  CA2  CA3
DA    78   12   43
AI    37   88    3
AS    87   20   71
DIA    6  100   93

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, DA to DIA
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CA1     4 non-null      int32
 1   CA2     4 non-null      int32
 2   CA3     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes


In [6]:
b=np.random.choice(a,p=[0.1,0.3,0.2,0.4],size=4)
a

array([2, 6, 5, 2])

In [3]:
a=[1,2,5,6]