# Numpy (Numerical python)

In [2]:
import numpy as np
print(np.__version__)#it prints the version if the numpy exists in the pc

1.23.5


In [2]:
#single dimesional arry
import numpy as np
ar= np.array((1,2,3,4))#sntax for creating array var=np.array()
ar2= np.array([1,2,3,4])
print(ar)
print(ar2)

[1 2 3 4]
[1 2 3 4]


# coverting list into array

In [3]:
list=[1,2,3]
array=np.array([1,2,3])
type(array)

numpy.ndarray

In [5]:
array_list=np.array(list)
type(array_list)

numpy.ndarray

# array dimensions

In [5]:
# two dimension array
two_dim=np.array([[1,2,3],[4,5,6]])
print(two_dim)

[[1 2 3]]


In [8]:
#three dimensional array
three_dim=np.array([[[1,2,3]]])
print(three_dim.ndim)

3


In [14]:
#ndim() print the dimension of the array
print(two_dim.ndim)
print(three_dim.ndim)

2
3


# creation using functions

In [5]:
#      start stop
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#      startstopstep
np.arange(0,10,2)

TypeError: arange: scalar arguments expected instead of a tuple.

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
#       rows cols 
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#       rows cols 
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
#        startstopvalue 
np.linspace(0,10,2)#it prints the 3 values with equal difference between 0 to 10

array([ 0., 10.])

In [23]:
#        startstopvalue 
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

# Matrix

In [15]:
#for creating identical matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
            #rows cols
np.random.randn(5,5)#it prints random values(0 to 1) between 5 to 5

array([[ 1.74929733, -1.71108341, -0.34982395,  0.5285462 ,  0.41361971],
       [ 0.36412193,  1.21590244, -0.74027929, -0.7373328 ,  1.54875363],
       [-1.55582003, -0.44842782, -1.72200775,  0.04686022,  1.19647476],
       [ 1.99629785, -0.20343071, -1.70399078,  0.78176648, -1.89243928],
       [ 1.56817353,  0.35967273,  1.09259148,  0.28413826, -0.07424879]])

# array

In [31]:
#               start stop values
np.random.randint(1,100,10)#it prints random values 

array([17, 51, 17, 74, 64, 86, 30,  7, 31, 43])

In [33]:
np.random.seed(0)#it will repeats the same value
np.random .randn(2)

array([1.76405235, 0.40015721])

In [21]:
np.random.seed(0)#it will repeats the same value
np.random .randint(2,4,2)

array([2, 3])

In [24]:
np.random.seed(0)#random seed stores the random value
np.random .randint(2,4,2)

array([2, 3])

In [25]:
np.random.seed(4)#it will repeats the same value
np.random .randint(2,4,2)

array([2, 2])

In [27]:
arr=np.arange(25)
print(arr)
arr2=np.random.randint(0,50,10)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 5  1 40 23  8  9 39 45 30 40]


In [30]:
#        rows cols
arr2=arr.reshape(5,5)#it will reshapes the array into matrix 5x2=10 numbers
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
#          row cols
arr2.reshape(2,5)#it will reshapes from matrix into arraay

array([[ 3,  3, 39,  9, 19],
       [21, 36, 23,  6, 24]])

# Some mathematical functions

In [56]:
arr2.max()#it returns the max value from arr2 variable

39

In [57]:
arr2.argmax()#it returns the idex value of the max value

2

In [58]:
arr2.min()#it returns the min value

3

In [59]:
arr2.argmin()#it returns the idex value of the min value

0

In [15]:
arr2=np.random.randint(0,50,10)
#        rows cols
arr2=arr2.reshape(5,2)
arr2.shape

(5, 2)

In [16]:
arr2.dtype #dimesion type with value

dtype('int32')

In [32]:
type(arr2)

numpy.ndarray

# Accesing

In [63]:
arr2[4]

19

In [18]:
a=np.array([1.2,1.3,1.4])
a[1:2]#n-1

array([1.3])

# slicing

In [39]:
#it overwrites the the values from 2:6(n-1)=2:5
arr=np.arange(1,10)
arr[2:6]=20
arr

array([ 1,  2, 20, 20, 20, 20,  7,  8,  9])

In [17]:
ar=np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
ar2=ar[0:6]
ar2

array([0, 1, 2, 3, 4, 5])

In [19]:
ar2[:]=30
ar2

array([30, 30, 30, 30, 30, 30])

In [20]:
ar

array([30, 30, 30, 30, 30, 30,  6,  7,  8,  9])

In [21]:
rr=ar2.copy()
rr2=ar2
rr2

array([30, 30, 30, 30, 30, 30])

In [78]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
c[1]

array([4, 5, 6])

In [80]:
c[1][0]#first row 0th index value

4

In [81]:
c[1][1]

5

In [82]:
c[:2,1:]

array([[2, 3],
       [5, 6]])

In [83]:
c[:2,:1]

array([[1],
       [4]])